apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: br-dhcp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: br-dhcp
    spec:
      hostNetwork: true
      hostPID: true

      containers:
      - name: br-dhcp
        image: kvaps/br-dhcp
        env:
        - name: BRIDGE
          value: "vmbr0"
        - name: VLAN
          value: "100"
        - name: IFACE
          value: "bond0"
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        volumeMounts:
        - name: cni-run
          mountPath: /run/cni
        - name: cni-cfg
          mountPath: /etc/cni/net.d
        - name: cni-bin
          mountPath: /opt/cni/bin
      volumes:
        - name: cni-run
          hostPath:
            path: /run/cni
        - name: cni-cfg
          hostPath:
            path: /etc/cni/net.d
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
