apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bridget
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: bridget
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      hostNetwork: true
      hostPID: true
      containers:
      - name: bridget
        image: kvaps/bridget
        env:
        - name: BRIDGE
          value: "cbr0"
        #- name: VLAN
        #  value: "4"
        #- name: IFACE
        #  value: "eth0"
        #- name: MTU
        #  value: "1500"
        #- name: POD_NETWORK
        #  value: "10.244.0.0/16"
        #- name: DIVISION_PREFIX
        #  value: "24"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: cni-cfg
          mountPath: /etc/cni/net.d
      volumes:
        - name: cni-cfg
          hostPath:
            path: /etc/cni/net.d
