apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: bridged
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: bridged
    spec:
      hostNetwork: true
      hostPID: true

      containers:
      - name: bridged
        image: kvaps/bridged
        env:
        - name: BRIDGE
          value: "cbr0"
        - name: VLAN
          value: "4"
        - name: IFACE
          value: "bond0"
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: cni-cfg
          mountPath: /etc/cni/net.d
      volumes:
        - name: cni-cfg
          hostPath:
            path: /etc/cni/net.d
